src/objects/AccountUserRole__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account User Roles</relationshipLabel>
        <relationshipName>AccountUserRoles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Relationship Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>AccountUserRoles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account User Role</label>
    <nameField>
        <displayFormat>UR-{0000}</displayFormat>
        <label>AccountUserRole Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AccountUserRoles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/OppTriggerTestClass.cls
@istest(seealldata = true)
class OppTriggerTestClass
{
    private static testmethod void oppTriggTestmethod()
    {
       
        Account acc = new Account();
        acc.name = 'Test Account';
        insert acc;
        
        
        AccountUserRole__c asr = new  AccountUserRole__c();
        asr.account__c = acc.id;
        asr.user__c = UserInfo.getUserID();
        asr.role__c = 'Marketing';
        insert asr;
        
        AccountUserRole__c asr1 = new  AccountUserRole__c();
        asr1.account__c = acc.id;
        asr1.user__c = UserInfo.getUserID();
        asr1.role__c = 'Relationship Manager';
        insert asr1;
        
        AccountUserRole__c asr2 = new  AccountUserRole__c();
        asr2.account__c = acc.id;
        asr2.user__c = UserInfo.getUserID();
        asr2.role__c = 'Partner Services';
        insert asr2;
        
        
            Opportunity opp = new Opportunity();
            opp.name = 'Test opp';
            opp.stageName = '4-Closed Won';
            opp.closeDate = System.now().date();
            opp.accountID = acc.id;
            insert opp;
            
        
    }
}