src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <picklist>
            <picklistValues>
                <fullName>Sip to Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UFPC/Yum</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shop n Give</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Core</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>PlusMScore__c</fullName>
        <defaultValue>0</defaultValue>
        <label>+M Score</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Relationship Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner Services</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/Gift__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>gifts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>deal_id__c</fullName>
        <label>deal_id</label>
        <precision>11</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>giftee_id__c</fullName>
        <label>Giftee_id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Gift</label>
    <nameField>
        <label>Gift Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gifts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PlusMScore__c.object
<CustomObject>
    <fields>
        <fullName>CardHolder__c</fullName>
        <label>CardHolder</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>PlusMScores</relationshipLabel>
        <relationshipName>PlusMScores</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PLusMNumber__c</fullName>
        <label>PLusMNumber</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>PlusMScore</label>
    <nameField>
        <label>PlusMScore Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PlusMScores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProgramEnrollment__c.object
<CustomObject>
    <fields>
        <fullName>CustomerID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer ID</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>ProgramEnrollments</relationshipLabel>
        <relationshipName>ProgramEnrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>ProgramEnrollments</relationshipLabel>
        <relationshipName>ProgramEnrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ProgramEnrollment</label>
    <nameField>
        <displayFormat>PE No. -{0000}</displayFormat>
        <label>ProgramEnrollments Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ProgramEnrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Transaction__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CardHolder__c</fullName>
        <label>CardHolder</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Card Holder</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <picklist>
            <picklistValues>
                <fullName>PurchaseOrder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>POS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>date1__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TRNS No. - {0000}</displayFormat>
        <label>Transaction</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestclasforTriggers.cls
@IsTest
public class TestclasforTriggers
{
public static testmethod void mytest()
{
  Program__c pr=new program__C(name='test pr');
  Insert Pr;
  Account acc=new Account(name='test accc');
  insert acc;
  contact con=new contact(lastname='test lastname',Accountid=acc.id,role__c =  'Marketing');
  insert con;
  contact con1=new contact(lastname='test lastname',Accountid=acc.id,role__c =  'Relationship Manager');
  insert con1;
  ProgramEnrollment__c PE=new ProgramEnrollment__c(CustomerID__c=con.id,Program__c=pr.id);
  insert PE;
  
  list<Transaction__c> trlist=new list<Transaction__c>();
  //for(integer i=0;i<1000;i++)
  //{
  Transaction__c Tr=new Transaction__c(date1__c=system.today(),amount__C=500,Program__c=pr.id,Contact__c=con.id,Transaction_Type__c='POS');
  //trlist.add(Tr);
  // }
 // insert trlist;
  insert Tr;
  
  Transaction__c Tr1=new Transaction__c(date1__c=system.today(),amount__C=700,Program__c=pr.id,Contact__c=con.id,Transaction_Type__c='POS');
  insert Tr1;
    Tr1.Transaction_Type__c='PurchaseOrder';
  update Tr1;
  Delete Tr1;
  

  
  Transaction__c Trns=new Transaction__c(date1__c=system.today(),amount__C=700,Program__c=pr.id,Contact__c=con.id,Transaction_Type__c=null);
   insert Trns;
   update Trns;
//Test cases for Gift

Gift__c gif=new Gift__c(contact__c=con.id,giftee_id__c='gt11',deal_id__c=11);
insert Gif;
update Gif;
//Test cases for PlusMScore

PlusMScore__c  pm=new PlusMScore__c (Contact__c=con.id,PLusMNumber__c=12,CardHolder__c='test');
insert pm;
update pm;

//Test case opportunity Closed-Won

Opportunity opp=new Opportunity (name='test',accountid=acc.id,closedate=system.today(),stagename='Prospecting');
insert opp;
//con.role__c =  'Relationship Manager';
//update con;

//opp.StageName = '4-Closed Won';
//update opp;

}

}